spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual 
    
    
    
conf-queue-exchange: 
  queue-movie-drama: q.movie-drama
  queue-movie-thriller: q.movie-thriller
  queue-movie-all: q.movie-all
  queue-movie-dlq: q.movie.dlq            
  exchange-movies: x.movies
  exchange-movies-dlx: x.movies.dlx

 
  
