spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual 
    
    
    
conf-queue-exchange: 
  queue-movie-drama: q.movie-drama
  queue-movie-thriller: q.movie-thriller
  queue-movie-all: q.movie-all
  queue-movie-dlq: q.movie.dlq
  queue-no-consumer-available: q.no-consumer-available            
  exchange-movies: x.movies
  exchange-movies-dlx: x.movies.dlx

conf-queue-exchange-direct-retry: 
  exchange-movies-work: x.movies.work
  exchange-movies-wait: x.movies.wait
  exchange-movies-dead: x.movies.dead
  queue-movie-drama-work: q.movie-drama.work
  queue-movie-drama-wait: q.movie-drama.wait
  queue-movie-drama-dead: q.movie-drama.dead
  queue-movie-thriller-work: q.movie-thriller.work
  queue-movie-thriller-wait: q.movie-thriller.wait
  queue-movie-thriller-dead: q.movie-thriller.dead
    
 
  
